# Generated by Django 6.0.5 on 2026-05-25 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('grant', 'Signup grant'), ('pick_purchase', 'Pick purchase'), ('pick_sale', 'Pick sale'), ('contest_entry', 'Contest entry'), ('contest_payout', 'Contest payout'), ('refund', 'Refund'), ('deposit', 'Deposit (real money)'), ('withdrawal', 'Withdrawal (real money)')], max_length=20)),
                ('ref_type', models.CharField(blank=True, max_length=40)),
                ('ref_id', models.BigIntegerField(blank=True, null=True)),
                ('balance_after', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='wallet.wallet')),
            ],
            options={
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
