# Generated by Django 6.0.5 on 2026-05-25 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.PositiveSmallIntegerField(choices=[(1, 'Over'), (2, 'Under'), (3, 'Home Line'), (4, 'Away Line'), (5, 'Home Ml'), (6, 'Away Ml')])),
                ('market', models.CharField(choices=[('totals', 'Totals'), ('spread', 'Spread'), ('moneyline', 'Moneyline')], editable=False, max_length=12)),
                ('line_point', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('odds_price', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss'), ('push', 'Push')], default='pending', max_length=8)),
                ('accustat_points', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='catalog.match')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('author', 'match', 'market'), name='one_pick_per_market_per_game')],
            },
        ),
    ]
