# Generated by Django 6.0.5 on 2026-05-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('category', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('odds_api_key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('home', models.CharField(max_length=80)),
                ('away', models.CharField(max_length=80)),
                ('commence_time', models.DateTimeField(db_index=True)),
                ('status', models.IntegerField(choices=[(0, 'Open for picks'), (1, 'Locked'), (10, 'Final (scored)'), (20, 'Settled')], db_index=True, default=0)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('over_under', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('over_extra', models.IntegerField(blank=True, null=True)),
                ('under_extra', models.IntegerField(blank=True, null=True)),
                ('home_rl', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('away_rl', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('home_rl_extra', models.IntegerField(blank=True, null=True)),
                ('away_rl_extra', models.IntegerField(blank=True, null=True)),
                ('home_ml', models.IntegerField(blank=True, null=True)),
                ('away_ml', models.IntegerField(blank=True, null=True)),
                ('line_book', models.CharField(blank=True, max_length=40)),
                ('line_updated_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='catalog.sport')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['commence_time'],
            },
        ),
    ]
