# Generated by Django 6.0.5 on 2026-05-26 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espn_id', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('logo_url', models.URLField(blank=True)),
                ('record', models.CharField(blank=True, max_length=20)),
                ('standing', models.CharField(blank=True, max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='catalog.sport')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.team'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['sport', 'name'], name='catalog_tea_sport_i_fef5bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('sport', 'espn_id'), name='uniq_sport_espn_team'),
        ),
    ]
