# Generated by Django 6.0.5 on 2026-05-25 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('entry_fee', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for entries'), ('running', 'Running'), ('settled', 'Settled')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.sport')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('payout', models.IntegerField(default=0)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='contests.contest')),
                ('entry_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.ledgerentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank', '-score'],
            },
        ),
        migrations.CreateModel(
            name='ContestGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_games', to='contests.contest')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.match')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='games',
            field=models.ManyToManyField(related_name='contests', through='contests.ContestGame', to='catalog.match'),
        ),
        migrations.CreateModel(
            name='ContestPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.PositiveSmallIntegerField(choices=[(1, 'Over'), (2, 'Under'), (3, 'Home Line'), (4, 'Away Line'), (5, 'Home Ml'), (6, 'Away Ml')])),
                ('market', models.CharField(choices=[('totals', 'Totals'), ('spread', 'Spread'), ('moneyline', 'Moneyline')], editable=False, max_length=12)),
                ('line_point', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('odds_price', models.IntegerField()),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('win', 'Win'), ('loss', 'Loss'), ('push', 'Push')], default='pending', max_length=8)),
                ('accustat_points', models.FloatField(blank=True, null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='contests.contestentry')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.match')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contestentry',
            constraint=models.UniqueConstraint(fields=('contest', 'user'), name='one_entry_per_user_per_contest'),
        ),
        migrations.AddConstraint(
            model_name='contestgame',
            constraint=models.UniqueConstraint(fields=('contest', 'match'), name='uniq_contest_match'),
        ),
        migrations.AddConstraint(
            model_name='contestpick',
            constraint=models.UniqueConstraint(fields=('entry', 'match', 'market'), name='one_contest_pick_per_market'),
        ),
    ]
